# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import detection_pb2 as detection__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in detection_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DetectionServiceStub(object):
    """============================================================
    检测服务定义
    ============================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Detect = channel.unary_unary(
                '/detection.DetectionService/Detect',
                request_serializer=detection__pb2.DetectRequest.SerializeToString,
                response_deserializer=detection__pb2.DetectResponse.FromString,
                _registered_method=True)
        self.DetectChange = channel.unary_unary(
                '/detection.DetectionService/DetectChange',
                request_serializer=detection__pb2.ChangeDetectRequest.SerializeToString,
                response_deserializer=detection__pb2.ChangeDetectResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/detection.DetectionService/HealthCheck',
                request_serializer=detection__pb2.HealthRequest.SerializeToString,
                response_deserializer=detection__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.GetVersion = channel.unary_unary(
                '/detection.DetectionService/GetVersion',
                request_serializer=detection__pb2.VersionRequest.SerializeToString,
                response_deserializer=detection__pb2.VersionResponse.FromString,
                _registered_method=True)


class DetectionServiceServicer(object):
    """============================================================
    检测服务定义
    ============================================================
    """

    def Detect(self, request, context):
        """通用检测接口
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectChange(self, request, context):
        """变化检测接口（algorithm_id=13）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVersion(self, request, context):
        """获取版本信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DetectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Detect': grpc.unary_unary_rpc_method_handler(
                    servicer.Detect,
                    request_deserializer=detection__pb2.DetectRequest.FromString,
                    response_serializer=detection__pb2.DetectResponse.SerializeToString,
            ),
            'DetectChange': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectChange,
                    request_deserializer=detection__pb2.ChangeDetectRequest.FromString,
                    response_serializer=detection__pb2.ChangeDetectResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=detection__pb2.HealthRequest.FromString,
                    response_serializer=detection__pb2.HealthResponse.SerializeToString,
            ),
            'GetVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersion,
                    request_deserializer=detection__pb2.VersionRequest.FromString,
                    response_serializer=detection__pb2.VersionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'detection.DetectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('detection.DetectionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DetectionService(object):
    """============================================================
    检测服务定义
    ============================================================
    """

    @staticmethod
    def Detect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/detection.DetectionService/Detect',
            detection__pb2.DetectRequest.SerializeToString,
            detection__pb2.DetectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectChange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/detection.DetectionService/DetectChange',
            detection__pb2.ChangeDetectRequest.SerializeToString,
            detection__pb2.ChangeDetectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/detection.DetectionService/HealthCheck',
            detection__pb2.HealthRequest.SerializeToString,
            detection__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/detection.DetectionService/GetVersion',
            detection__pb2.VersionRequest.SerializeToString,
            detection__pb2.VersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
